image:
  repository: __Repository__
  tag: __BuildNumber__

secrets:
  connectionstrings:
    ConnectionStrings__CustomerDatabase: __ConnectionString__
    AzureServiceBus__ConnectionString: __AzureServiceBusConnectionString__

probes:
  enabled: true

imagePullSecrets:
  - name: acr-secret

#service:
#  type: ClusterIP
  
ingress:
  enabled: __IngressEnabled__
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  namespace: __K8sNamespace__
  path: /  
  pathType: Prefix
  hosts:
    - __URL__
  tls:
    - secretName: __TlsSecretName__
      hosts:
        - __URL__

envvariables:
  TenantId: __TenantId__
  useAadAuthentication: __UseAadAuthentication__

aadAuthentication:
  managedIdentityId: __ManagedIdentityId__
  managedIdentityClientId: __ManagedIdentityClientId__  
  managedIdentityName: __Managedidentity-aks__