image:
  repository: __Repository__
  tag: __BuildNumber__

secrets:
  connectionstrings:
    ConnectionStrings__CustomerDatabase: __ConnectionString__
    AzureServiceBus__ConnectionString: __AzureServiceBusConnectionString__

probes:
  enabled: true

imagePullSecrets:
  - name: acr-secret