image:
  repository: __Repository__
  tag: __BuildNumber__

secrets:
  connectionstrings:
    ConnectionStrings__OrderDatabase: __ConnectionString__

probes:
  enabled: true

imagePullSecrets:
  - name: acr-secret