image:
  repository: __Repository__
  tag: __BuildNumber__

secrets:
  connectionstrings:
    ConnectionStrings__OrderDatabase: __ConnectionString__

probes:
  enabled: true

imagePullSecrets:
  - name: acr-secret

#service:
#  type: ClusterIP
  
ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true" 
  namespace: __K8sNamespace__
  path: /orderapi-test/?(.*)